### ISSUE TITLE
Contact page is out of proportion for mobile

### ISSUE THREAD

**Issue by Mahadhevha** [Epicalable/epicalable.github.io#3]
![Screenshot_20220806-160148_Chrome.jpg](https://user-images.githubusercontent.com/69076784/183240333-a6dba923-e976-4c92-89af-b9c3945fca09.jpg)

**Comment by CodingAviator** [comment]
Thanks for your input we will try to remedy this issue for our mobile users.

**Comment by CodingAviator** [comment]
We have fixed this in the latest commit.
