### ISSUE TITLE
Parallax Scrolling Effect

### ISSUE THREAD

**Issue by CodingAviator** [Epicalable/epicalable.github.io#4]
Parallax is a 3d effect used in various websites to make webpages attractive. In this effect, as we scroll, the background of the webpages moves at a different speed than the foreground making it look brilliant to the eyes. This effect is a great visual but an easy method to implement with the help of CSS.

**Comment by Mahadhevha** [comment]
We at Epicalable are 100% commited to helping out requests and issues from our users, but due to the limited research and experience so far, we have decided to put this on hold for now till we can find the appropriate solution.

**Comment by Mahadhevha** [comment]
Once when a solution is made this thread will be opened again.
