### ISSUE TITLE
Any issues?

### ISSUE THREAD

**Issue by Mahadhevha** [Epicalable/epicalable.github.io#5]
As there is currently no planned development for this website I want to make sure that all of our users currently have no noticible issues.

If there is please comment below.

Thank you.

**Comment by EpicRD** [comment]
![Screenshot_20230512_005204_Chrome.jpg](https://github.com/Epicalable/epicalable.github.io/assets/119758164/48c7d496-69d3-4c64-a5b1-bad9435c4877)

![Screenshot_20230512_005230_Chrome.jpg](https://github.com/Epicalable/epicalable.github.io/assets/119758164/0b5041d9-ab5c-48ef-97fe-294adc76263d)


New Epicalable logos 🥳🥳🥳
